### ISSUE TITLE
Entities Mode: Deterministic Coloring Sequence in Entities Mode

### ISSUE THREAD

**Issue by Abhishek-P** [gucorpling/gitdox#163]
The coloring sequence is non-deterministic and changes once refershed or saved. 
This is a problematic if you are doing annotations with frequent saves.

**Comment by amir-zeldes** [comment]
Hm, this is an interesting point, thanks for bringing it up. It's not exactly that the coloring isn't deterministic: it's always assigned in the same order (first cluster is red, second is blue...). But if you delete a cluster/change it so another one becomes the earliest one encountered by the module, then that first one will become red, second blue, etc. The initial colors are the most distinguishable ones, and subsequent ones et less and less distinct, which is inevitable as the document has more clusters.

I see two challenges to changing this: one is that we might end up retaining suboptimal colors if we retain badly distinguishable ones when a 'good' color distinct cluster has been deleted. The second is a technical issue: you would need to store the color assignment somewhere, but none of the formats we work with (Webanno TSV, TT SGML) have a built-in capability of doing this, so you'd need to do something outside of the serialization formats. 

If you're interested in looking into this and trying to propose/implement a fix I'd be open to that, but otherwise this is sadly probably a 'wontfix'...

**Comment by Abhishek-P** [comment]
I expected that may have been the case. 
Engineering was I was considering something like a session local coloring scheme. 

 You should go ahead and mark it `wontfix`. 
 
 I will try to peek at the coloring scheme nonetheless, I am curious how it works
